### ISSUE TITLE
API coursework creation

### ISSUE THREAD

**Issue by Panther-12** [codeHack-s/last-codehack#1]
Hello @Raccoon254  , I would like to be tasked with creation of the API coursework...
<img width="488" alt="postman" src="https://github.com/codeHack-s/last-codehack/assets/87605179/6bfacc2b-571d-4640-a6ff-da89b804856e">

**Comment by Raccoon254** [comment]
Yep please just go on with that.
Just create a folder for that

**Comment by Panther-12** [comment]
> Yep please just go on with that. Just create a folder for that

Ok
